/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Assets_Create = require('./code/before-assets-create');
const before_Assets_Update = require('./code/before-assets-update');
const after_Assets_Read = require('./code/after-assets-read');
const before_Purchaseorders_Create = require('./code/before-purchaseorders-create');
const before_Purchaseorders_Update = require('./code/before-purchaseorders-update');
const on_Assets_Retire = require('./code/on-assets-retire');
const on_Assets_Valuatedepreciation = require('./code/on-assets-valuatedepreciation');
const on_Assets_Monthendclosing = require('./code/on-assets-monthendclosing');
const on_Assets_Yearendclosing = require('./code/on-assets-yearendclosing');
const before_Legacyassets_Create = require('./code/before-legacyassets-create');

class assetmanagementSrv extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'Assets', async (request) => {
            await before_Assets_Create(request);
        });

        this.before('UPDATE', 'Assets', async (request) => {
            await before_Assets_Update(request);
        });

        this.after('READ', 'Assets', async (results, request) => {
            await after_Assets_Read(results, request);
        });

        this.before('CREATE', 'PurchaseOrders', async (request) => {
            await before_Purchaseorders_Create(request);
        });

        this.before('UPDATE', 'PurchaseOrders', async (request) => {
            await before_Purchaseorders_Update(request);
        });

        this.on('retire', 'Assets', async (request) => {
            return on_Assets_Retire(request);
        });

        this.on('valuatedepreciation', 'Assets', async (request) => {
            return on_Assets_Valuatedepreciation(request);
        });

        this.on('monthendclosing', 'Assets', async (request) => {
            return on_Assets_Monthendclosing(request);
        });

        this.on('yearendclosing', 'Assets', async (request) => {
            return on_Assets_Yearendclosing(request);
        });

        this.before('CREATE', 'LegacyAssets', async (request) => {
            await before_Legacyassets_Create(request);
        });

        return super.init();
    }
}


module.exports = {
    assetmanagementSrv
};